name: Update Data
on:
  schedule:
    - cron: '*/1 * * * *' # كل دقيقة
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install requests
        run: pip install requests
      - name: Run script
        env:
          TRADIER_TOKEN: ${{ secrets.TRADIER_TOKEN }}
        run: python update_data.py
      - name: Commit changes
        run: |
          git config --global user.name "Sniper Bot"
          git config --global user.email "bot@github.com"
          git add options_data.json
          git commit -m "Auto update data" || exit 0
          git push
